### PR TITLE
DependabotAlertDependencyUpdate - Dependabot Alert Dependency Update

### PR DESCRIPTION
**Pull request by DaleHerring**

### CODE REVIEW

**Comment by warmbowski** [comment]
@DaleHerring Sorry, I posted this message on the wrong PR originally. Now I have the correct one.  

Can you do me a favor and run jest tests and screenshot the output and add here? It looks like the tests are specific to your account and I can't run them. For the future, I think we should use a generic test user and run these against the test cluster, and not against prod.

Also, can you run npm run lint:fix? I see a bunch of little lint errors. Thanks.

**Comment by DaleHerring** [comment]
image

As for the test user, this is the way I was told to do it. I haven't touched this repo in awhile.

**Review by warmbowski — APPROVED** [review]
Awesome! thanks for doing posting the test results. 

LGTM!

**Comment by bnlb** [comment]
> image
> 
> As for the test user, this is the way I was told to do it. I haven't touched this repo in awhile. I just happened to see this dependency alert at midnight and decided to fix it.

This has come up multiple times now. I'll create a follow up ticket and assign to you to fix.

Screen Shot 2021-05-07 at 5 00 58 PM

**Comment by bnlb** [comment]
@DaleHerring https://algorithmia.atlassian.net/browse/DEV-297

**Pull request merged**
